name: ci
on: push

concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - &checkout
        name: Checkout sources
        uses: actions/checkout@v5

      - &setup-bun
        name: Setup Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - &install-deps
        name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint

  typecheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - *checkout

      - *setup-bun

      - *install-deps

      - name: Run type checks
        run: bun run typecheck
